#### Geoff
** See if you can come up with info on the number of trips to Cambridge and Somerville using GIS info.**

Here is the link to BoundingBox, although there are some limitations. Tim spoke about creating a mapping mask.

http://boundingbox.klokantech.com/

Thanks.

In [1]:
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
#import sqlite3
from scipy import stats

In [2]:
hubway_csv = pd.read_csv('./database/hubway_final.csv')
hubway_df = pd.DataFrame(hubway_csv)
hubway_df.head()

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,end station category,start station category,day_of_week
0,0,542,2015-01-01 00:21:44,2015-01-01 00:30:47,115,Porter Square Station,42.387995,-71.119084,96,Cambridge Main Library at Broadway / Trowbridg...,42.373379,-71.111075,277,Subscriber,1984,1,4,5,Thurs
1,1,432,2015-01-01 00:53:46,2015-01-01 01:00:58,115,Porter Square Station,42.387995,-71.119084,96,Cambridge Main Library at Broadway / Trowbridg...,42.373379,-71.111075,1307,Subscriber,1987,1,4,5,Thurs
2,2,580,2015-01-04 14:29:05,2015-01-04 14:38:45,115,Porter Square Station,42.387995,-71.119084,96,Cambridge Main Library at Broadway / Trowbridg...,42.373379,-71.111075,673,Subscriber,1991,1,4,5,Sun
3,3,754,2015-01-08 16:17:04,2015-01-08 16:29:39,115,Porter Square Station,42.387995,-71.119084,96,Cambridge Main Library at Broadway / Trowbridg...,42.373379,-71.111075,1092,Customer,1961,2,4,5,Thurs
4,4,667,2015-01-10 11:40:49,2015-01-10 11:51:57,115,Porter Square Station,42.387995,-71.119084,96,Cambridge Main Library at Broadway / Trowbridg...,42.373379,-71.111075,772,Subscriber,1980,1,4,5,Sat